export const defaultPitchSlides = [
  { id: 1, title: "Slide 1 — Title", content: "TRUTH PROTOCOL\n\nAction / Adventure / Conspiracy / Military Thriller\n\nWritten by\nMike Surick\n\nA man accidentally learns the most dangerous truths in human history. Now, the powers that be will stop at nothing to find him." },
  { id: 2, title: "Slide 2 — The Truth Protocol", content: "The Truth Protocol is a classified program designed to reveal humanity's deepest secrets to all who wish to know them, but only in the moments prior death by medically assisted euthanasia.\n\nArtificial Intelligence Systems International (AISI) is responsible for facilitating the program where participants are injected with a powerful neurotropic drug and connected to an advanced neural AI interface before being exposed to Truth Data — a hidden archive of suppressed intelligence, secret programs, and manipulated historical events.\n\nThe purpose of the program is simple:\n\nAllow the truth to be seen… and then die with the witness.\n\nUntil one mistake changes everything." },
  { id: 3, title: "Slide 3 — Michael Riley", content: "Michael R. Riley\n\nDecorated Special Forces veteran.\nElite tactical operator.\n\nAfter decades of combat deployments, Riley is trying to live a quiet life with his wife Michele and their daughter Lauren.\n\nBut Riley is about to become the most dangerous liability the Truth Protocol has ever faced." },
  { id: 4, title: "Slide 4 — The Accident", content: "After a minor car accident, Riley is hospitalized and mistakenly identified as a volunteer for the Truth Protocol.\n\nBefore anyone realizes the mistake, Riley is injected with the program's cognitive compound and connected to the neural interface.\n\nFor the first time in history the entire truth data archive is shown to the wrong person." },
  { id: 5, title: "Slide 5 — They Try to Kill Him", content: "Program operatives quickly realize the catastrophic mistake.\n\nRiley was never meant to see the data.\n\nTheir solution is immediate.\n\nEliminate the witness.\n\nBut Riley escapes the facility with Michele." },
  { id: 6, title: "Slide 6 — The Manhunt", content: "Riley and Michele go on the run as a covert operation is launched to hunt him down.\n\nAISI brings in rogue CIA SOG Operator Jack Turner to help find Riley.\n\nThe forces pursuing him include:\n\nAISI Corporate Security Contractors\nCIA Special Operations Group (SOG) assets\nCorporate black-site security teams\n\nThe goal: Kill or capture Riley before he can tell anyone what he saw." },
  { id: 7, title: "Slide 7 — The Ambush", content: "During a brutal roadside ambush, Riley and Michele fight off multiple SOG Operators.\n\nThe firefight leaves several operatives dead.\n\nBut Michele is fatally wounded.\n\nIn her final moments, she makes Riley promise to protect their daughter Lauren." },
  { id: 8, title: "Slide 8 — Riley Disappears", content: "Devastated and hunted, Riley reconnects with his former Special Forces brothers who trust him and know how to fight a war that officially doesn't exist." },
  { id: 9, title: "Slide 9 — They Take His Daughter", content: "Unable to locate Riley, Jack Turner and his team escalates the operation.\n\nThey abduct Riley's daughter Lauren.\n\nShe is taken to a classified black-site facility and held as leverage.\n\nThe message to Riley is clear:\n\nSurrender… or she dies." },
  { id: 10, title: "Slide 10 — Richard Sullivan", content: "Richard Sullivan\nSenior Security Operations executive at AISI.\n\nFor years, Sullivan has helped oversee the Truth Protocol.\n\nBut Riley's escape forces him to question everything.\n\nWhen Lauren is kidnapped to lure Riley into the open, Sullivan realizes the organization has crossed a line.\n\nInstead of helping eliminate Riley…\n\nSullivan secretly decides to help him.\n\nHe helps Riley identify the black-site facility holding Lauren.\n\nFor the first time, someone inside the system turns against it." },
  { id: 11, title: "Slide 11 — The Counterattack", content: "Riley agrees to surrender. He will trade his life for Lauren's.\n\nBut is that really his plan?\n\nHe and the remaining member of his old Special Forces team put together a plan to rescue Lauren.\n\nThe hunted becomes the hunter." },
  { id: 12, title: "Slide 12 — The Final Mission", content: "A high-risk tactical assault to rescue Lauren and destroy the program that started it all.\n\nA mission complete with Blackhawk assault, fast roping to the objective, breeching and clearing, all in the name of brotherhood and duty.\n\nOf course, in the real world, nothing ever goes as planned and not everyone makes it home.\n\nBut who is it?" },
  { id: 13, title: "Slide 13 — Key Cinematic Moments", content: "The Hospital Mistake\nRiley is accidentally subjected to the Truth Protocol.\n\nThe Escape\nRiley fights his way out of the hospital.\n\nThe Roadside Ambush\nMichele is killed during a violent assault.\n\nLauren's Kidnapping\nJack Turner abducts Lauren to force him into the open.\n\nThe Black-Site Assault\nRiley and his team launch the tactical assault to rescue Lauren." },
  { id: 14, title: "Slide 14 — Tone", content: "Grounded\nRelentless\nEmotionally driven\nHigh-stakes tactical action\n\nComparable to:\n\nThe Bourne Identity\nSicario\nZero Dark Thirty\nJack Ryan" },
  { id: 15, title: "Slide 15 — Closing", content: "The Truth Protocol was designed to ensure the truth died with its witnesses.\n\nBut one man survived." }
];
